### PR TITLE
updates documentation with region not found error

### PR DESCRIPTION
**Pull request by MatteoPierro**
Adds information to the Readme in order to solve the region not found error.

### CODE REVIEW

**Comment by phuonghuynh** [comment]
@ronaldtse could you review this update? Pls do `Rebase and Merge` if its ok
screenshot at aug 02 13-37-55

**Comment by ronaldtse** [comment]
@MatteoPierro thanks for this. @phuonghuynh sorry I missed your message earlier.

This makes me think the correct solution is to allow selection of the region in the interface where we add the queue. For example, you could have a queue in `us-east-1` but also another in `eu-east-1`. We can fetch the region list from AWS API (i.e. which regions support SQS).

What do you think?

**Comment by ronaldtse** [comment]
@MatteoPierro please feel free to let us know any other problems you encounter with the plugin. Thank you again for your contribution!

**Comment by MatteoPierro** [comment]
@ronaldtse I agree with you that the correct solution is to allow the region selection in the user interface.

**Comment by ronaldtse** [comment]
Appreciate your thoughts @MatteoPierro !

**Comment by phuonghuynh** [comment]
@ronaldtse could we implement this ?

**Comment by ronaldtse** [comment]
@phuonghuynh please do, thanks!

**Pull request merged**
